
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxxgraztgbilpylfcuvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4eGdyYXp0Z2JpbHB5bGZjdXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDQ0MDIsImV4cCI6MjA1OTMyMDQwMn0.W26bjxeTF_BK8WU293vCQ8X3VLnWLL19f6cZehrOiz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
